### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by 4lexBaum** [tcort/markdown-link-check#1]
Hi I get a unhandled error while running the check:

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open 'C:\dev\null'
    at Error (native)

If all links are realy alive the test works.

Have you any ideas?

**Comment by tcort** [comment]
This is a portability issue with the way the link checking is done. When `HEAD` fails, a `GET` is attempted. The output of the `GET` is streamed to `/dev/null`. This is done  to prevent a large file from using up all of the memory (e.g. a GNU/Linux Distribution DVD ISO). It seems that Microsoft Windows doesn't have a `/dev/null` and this causes an exception to occur. I read on the [gcc mailing list](https://gcc.gnu.org/ml/gcc-patches/2005-05/msg01793.html) that naming a file `nul` will have the same effect.

I'll try to get that change completed, tested, and published in the next couple of days.

**Comment by tcort** [comment]
I've released version 2.0.1 of `markdown-link-check` which includes a fix for this issue which I've tested on Windows XP. If the problem persists after upgrading, please re-open this issue.

Thanks for the bug report!
