### ISSUE TITLE
Add Throttling

### ISSUE THREAD

**Issue by bnb** [tcort/markdown-link-check#101]
Currently if you try to test a project with _a lot_ of links to GitHub.com, you'll get rate limited pretty aggressively. It would be ideal if requests could be batched/throttled so that's not hit. 😅 

Ref: https://github.com/nodejs/community-committee/pull/640/checks?check_run_id=995759237

**Comment by NicolasMassart** [comment]
@bnb your workaround with the headed seems nice, I wonder how I could get it done with Circle CI (I have doubts on the Token generation part), but for a real fix on MD Link checker it would be probably better to take the HTTP 429 and retry headers in account in link checker and push these links to a retry queue.

**Comment by bnb** [comment]
I've not actually been able to get the workaround to work. I need to invest some more time in it since the file would need to be custom generated every time since the config can only be JSON (as opposed to JS which would minimize the work there, since I need to pass a GitHub Secret every time).

**Comment by NicolasMassart** [comment]
I pushed a PR for this #106 
Hopefully it will be merged.
