### ISSUE TITLE
Ignore subpaths

### ISSUE THREAD

**Issue by bnb** [tcort/markdown-link-check#102]
I have a use case where I want to check all links in the current directory *except for* a single path that has a lot of static markdown. It would be really nice if I could ignore/skip directories. It seems that this functionality is currently not supported outside of running against individual files and directories while _excluding_ the one I don't want results for.

**Comment by NicolasMassart** [comment]
I confirm that we don't have path exclusion yet.
Multiple options are possible:
- add a feature to handle an ignore file like the .gitignore one but named .markdownlinkignore that would list globs (path able to include * wildcard) to ignore.
- a configuration with path patterns to ignore similar to the link ignore pattern configuration.

**Comment by guettli** [comment]
This feature would be great.
