### ISSUE TITLE
Stored Docker Image

### ISSUE THREAD

**Issue by cadeef** [tcort/markdown-link-check#110]
I've started using github-action-markdown-link-check for a personal site and noticed the majority of time executing is while building the docker image.

Would it be feasible to implement an image build that's stored in Github Packages on merge? I realize it isn't directly related to the project, but a fix would trickle downstream. @gaurav-nelson would probably have an opinion too.

Happy to submit a pull request if it's something that interests folks.

**Comment by NicolasMassart** [comment]
We definitely need CI that publishes Docker image and NPM package on merge in master and release/tag

**Comment by cadeef** [comment]
Ok, I’ll take it on.

I recommend building images regardless of the release context by tagging the commit SHA and then implementing a separate workflow for release tagging. The benefit being that commits generate their own images which can be used in additional integration testing.

**Comment by cadeef** [comment]
Decided it would be best to submit 2 PRs for this issue-- Docker & NPM. I haven't packaged for NPM before and it might be a bit more finagling.

Additionally, I have another PR nearly ready to go that addresses making the Docker image ready for public consumption.

**Comment by NicolasMassart** [comment]
First PR #113 is merged.

**Comment by NicolasMassart** [comment]
Congrats @cadeef and thanks @tcort for your help on this!
We now have a docker image build on master 🥳
