### ISSUE TITLE
Don't check the same URL multiple times

### ISSUE THREAD

**Issue by chriselion** [tcort/markdown-link-check#111]
Following up from a [comment](https://github.com/tcort/markdown-link-check/issues/78#issuecomment-698994066)

If the same URL appears twice in a file, you can cache the results of the first check and not check it again.

Ideally if we could pass multiple files at once, this caching would persist across files.

**Comment by sanmai-NL** [comment]
The initial solution can be simple and without persistent caching: keep a dictionary/mapping URL -> status outside the file loop.

**Comment by tcort** [comment]
There's an open task for this [link-check issue #31](https://github.com/tcort/link-check/issues/31). Feel free to implement it and submit a PR. It'd be a nice feature to have.
