### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by Southclaws** [tcort/markdown-link-check#120]
Great tool!

We have a Docusaurus site and images are stored locally in /static/images, I used a pattern replace to add the /static but it seems this checker doesn't check local files, only remote (it complained about a HTTP error or something when trying to check image URLs)

```
ERROR: 11 dead links found!
[✖] ./static/images/contributing/edit-this-page.png → Status: 400
```

I also tried `/`

```
ERROR: 11 dead links found!
[✖] static/images/contributing/edit-this-page.png → Status: 400
```

Thanks!

**Comment by nschonni** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors
Sounds like Docosaurus might be returning a bad response

**Comment by Southclaws** [comment]
Docusaurus isn't running, I'm just doing it on Markdown files

**Comment by NicolasMassart** [comment]
@Southclaws could paste the replacement pattern config here please?

**Comment by Southclaws** [comment]
I believe it was `^/static/`, but I don't have it any more.

**Comment by NicolasMassart** [comment]
Do you still need this to be fixed? If so, you have to provide detail to help us. Thanks.

**Comment by Southclaws** [comment]
Ah I found the branch, I thought I never pushed!

https://github.com/openmultiplayer/wiki/blob/link-checker-action/mlc_config.json

I was trying to ignore images completely. I'll give it another shot today when I get time and report back.

**Comment by cadeef** [comment]
The reoccurring incidence of this class of issue suggests an opportunity for refinement. A couple ideas that may reduce/eliminate confusion:

- **Augment documentation with common workflows.** Users tend to stumble on the replacePattern functionality; it's powerful, common scenarios for use and recommendations would reduce time from install to functioning tests for many consumers of markdown-link-check.
- **Implement an explicit URI scheme.** As it is now, experience informs my knowledge of the implicit decisions in evaluating a given link. Take `/img/reallycoolimage.png` for instance, as a new user, how is MLC going to evaluate it? My intention and the program's are at odds. An explanation of the decision framework in the docs may be sufficient, but there's a better way-- consistent URI application. URIs make handling explicit. There is considerably less confusion if a replacement uses `file://img/reallycoolimage.png`. I know from the URI that it is looking for a local file at a location relative CWD.

These certainly aren't the only solutions but they're intended as food for thought.
