### ISSUE TITLE
Getting "Too Many Requests (HTTP error 429)" Error

### ISSUE THREAD

**Issue by praneesha** [tcort/markdown-link-check#130]
I am getting this "Too Many Requests (HTTP error 429)" Error in my Link Checker when calling to external sites as shown below.

<img width="958" alt="97883371-c8e26e00-1d4a-11eb-95c4-2d411a4c3548" src="https://user-images.githubusercontent.com/11707273/97957851-076f3b80-1dd2-11eb-961e-fa357b58c51c.png">

Is there a way to get this resolved or to skip displaying these in the output file using Liche arguments?

**Comment by NicolasMassart** [comment]
Did you activate 429 retry in your configuration?
See https://github.com/tcort/markdown-link-check#markdownlinkcheckmarkdown-opts-callback `retryOn429` option

**Comment by praneesha** [comment]
@NicolasMassart - I am using the [Link Checker written by Peter Evans](https://github.com/peter-evans/link-checker) and unfortunately the `-a` and `-r` arguments don't seem to work in it.

Do I have another workaround?

**Comment by NicolasMassart** [comment]
Well it has nothing to do with our project then...or I misunderstood... Can you explain how your issue is related to tcort/markdown-link-checkbif you don't use it?

**Comment by praneesha** [comment]
I am sorry, my bad. I opened this issue thinking this project can help me in case if it is also using Liche.

Will close it.
