### ISSUE TITLE
Timeout Option Not Explained

### ISSUE THREAD

**Issue by ThunderSon** [tcort/markdown-link-check#134]
Hello!
I saw that #129 is here to help with major issues with the timeout (I face them regularly, so thanks for this!).
Could we possibly add a point on this in the Readme doc mentioning if there is a default (doesn't seem like it as shown in the PR).

If you want me to add anything on this matter in the repo let me know, I'd love to help.

**Comment by NicolasMassart** [comment]
We did not do so good on doc obviously. Thanks for spotting this.
If you propose to help, you are absolutely welcome. You can fork this repos, make the changes on your fork in a new branch and then push them and create a pull request from this branch. We will review it carefully, I promise.
