### ISSUE TITLE
Is this possible to tag a new version to release latest feature?

### ISSUE THREAD

**Issue by boillodmanuel** [tcort/markdown-link-check#141]
Hi,

Is this possible to tag a new version to release latest feature? (I'm looking for custom timeout)

Thanks a lot,

Manuel

**Comment by NicolasMassart** [comment]
Hi @boillodmanuel!
We did not plan a release yet but thanks to remind us that it could be a nice idea.
Until then, feel free to use the latest version from the master.
if you are using NPM, `npm install --save tcort/markdown-link-check` will add the master branch version in your `package.json`.
Once the release will be out, you can switch to it of course.

**Comment by xtqqczze** [comment]
It would be great to have a release that includes #106.

**Comment by tcort** [comment]
I've published version `3.8.4`
