### ISSUE TITLE
Return version from CLI

### ISSUE THREAD

**Issue by nvuillam** [tcort/markdown-link-check#149]
Would it be possible to return the version from `markdown-link-check -v` ?

I would need it for a cleaner integration in Mega-Linter :) (for the moment I always display v0.0.0 by default )

![image](https://user-images.githubusercontent.com/17500430/103766865-ddc7d000-501f-11eb-9f2c-bff18d9d427c.png)

Thanks !

**Comment by NicolasMassart** [comment]
Until it's done, maybe you can extract it from the package-lock?

**Comment by nvuillam** [comment]
This is not blocking... and Mega-Linter architecture requires it to work with just command line... the script would be too awful :)

**Comment by tcort** [comment]
I've implemented this with the `-V` or `--version` flags. The `-v` flag is already taken for verbose. Thanks for the suggestion.
