### ISSUE TITLE
Fails to find page on wikipedia

### ISSUE THREAD

**Issue by hottomato4** [tcort/markdown-link-check#155]
When I include a link to the Wikipedia page on the `?:` syntax (ternary operator) at [https://en.wikipedia.org/wiki/%3F:](https://en.wikipedia.org/wiki/%3F:) it fails to find it even though it is up, possibly due to the odd url. 

Tested on the following file: 

```md
link to wikipedia's [ternary operator][ternary]

Another link to [Computer_programming]

[ternary]: https://en.wikipedia.org/wiki/%3F:

[Computer_programming]: https://en.wikipedia.org/wiki/Computer_programming
```

I get the following output:

```bash
$ docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:3.8.5 /tmp/ternary.md

FILE: /tmp/ternary.md
[✖] https://en.wikipedia.org/wiki/%3F:
[✓] https://en.wikipedia.org/wiki/Computer_programming

2 links checked.

ERROR: 1 dead links found!
[✖] https://en.wikipedia.org/wiki/%3F: → Status: 400
```

**Comment by NicolasMassart** [comment]
Issue linked to the addition of encoding check on the urls to prevent double encoding. As `?` is a valid url character (defines the start of param in URL) it's decoded but not reencoded. but then it becomes a param marker and is not just the regular char. Another strategy to prevent double encoding has to be used... I'm on it.

**Comment by NicolasMassart** [comment]
Note that this is clearly an issue at the link-check level, so I will close this one and create a new one on the link-check repos.
