### ISSUE TITLE
false 404 from parenthesis?

### ISSUE THREAD

**Issue by belorenz** [tcort/markdown-link-check#158]
m-l-c fails wit 404 when checking the  following link.

[http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29)

My guess is, this may be related with %28 '(' and %29 ')'
Can someone reproduce the error or knows a workaround?

Btw you are providing a very useful tool, thanks!

**Comment by belorenz** [comment]
I was able to fix this problem by reverting the url to 
[http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber(c++)](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber(c++))

**Comment by NicolasMassart** [comment]
That's strange, I fixed exactly this some times ago... you closed but I will still put this on my check list. escaped URLs should work.
