### ISSUE TITLE
Option to set project root

### ISSUE THREAD

**Issue by ionsquare** [tcort/markdown-link-check#16]
It would be very useful to have an option to set the project root when checking files.

For example, the current behaviour gives this:

```bash
~/code/project/scripts $ markdown-link-check README.md
[✖] /documentation/infrastructure-setup.md
[✓] ../documentation/infrastructure-setup.md
```

I'd really like to be able to do something like this:

```bash
~/code/project/scripts $ markdown-link-check --root .. README.md
[✓] /documentation/infrastructure-setup.md
[✓] ../documentation/infrastructure-setup.md
```

This is a valid path relative to the project root in github.

**Comment by timmkrause** [comment]
Achievable now with the replacementPatterns (#48).

**Comment by adrianmcli** [comment]
@timmkrause Wouldn't the project path have to be hardcoded then?

How do you make it so that it always refers to project root? Is there a `pwd` equivalent that I can put in there?

**Comment by adrianmcli** [comment]
@ionsquare did you figure out a way to do this?

Currently I am using [Docusaurus](https://github.com/facebook/docusaurus), which has a specific convention:

- All static files are inside a `static` folder like `<project_root>/static/img/hello.png`
- Inside my Markdown, I will write `![hello](/img/hello.png)` to refer to the above image

@timmkrause what is the replacement pattern I should use for this?

**Comment by adrianmcli** [comment]
@timmkrause It appears that the `file://`protocol does not support project root-specific paths. This means that this link checker will only ever work on one person's computer. For example, this setting works for me:

```
{
  "replacementPatterns": [
    {
      "pattern": "^/docs",
      "replacement": "file:///Users/adrianli/dev/docs/static/docs"
    }
  ]
}

```

But this will only ever work for a Mac user with the name of `adrianli`.
