### ISSUE TITLE
GitHub Dependabot cannot update marked to a non-vulnerable version

### ISSUE THREAD

**Issue by wkande** [tcort/markdown-link-check#161]
I think that **markdown-link-check** needs to update its dependency of **markdown-link-extractor** that in turn will get a newer version of **marked**?

Anyway it is upsetting GitHub Dependabot.

---

### From GitHub Dependabot

 Dependabot cannot update marked to a non-vulnerable version
The latest possible version that can be installed is 1.2.9 because of the following conflicting dependency:

markdown-link-check@3.8.6 requires marked@^1.1.1 via markdown-link-extractor@1.2.6
The earliest fixed version is 2.0.0.

View logs or learn more about troubleshooting Dependabot errors.

**Comment by tcort** [comment]
updated in `master`.

I'll roll a new release soon.

**Comment by wkande** [comment]
Great! Thanks for the quick update, and thanks for a good product.

**Comment by elaine24punto** [comment]
Dependalot or defendant these people are playing with children's lives. You need to report there movements. I guarantee it over the years. Money hides everything
