### ISSUE TITLE
Check whether all links are used

### ISSUE THREAD

**Issue by IlanCosman** [tcort/markdown-link-check#162]
Some links defined as labels may not be used in the document. It would be cool to detect these.

**Comment by IlanCosman** [comment]
On second thought this request would probably be better suited for something like markdownlint.

**Comment by nschonni** [comment]
I mostly use Markdownlint, but remark-lint does already have a rule for this https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-unused-definitions
