### ISSUE TITLE
Add recursive flag

### ISSUE THREAD

**Issue by adius** [tcort/markdown-link-check#20]
Very cool tool! 😁

But it would even be cooler if there was a `--recursive` flag to recursively check all links in linked markdown files. :wink:

**Comment by adius** [comment]
Or maybe it's not a good idea. It's really simple to achieve with the shell:

```fish
find . -iname '*md'| while read file; markdown-link-check $file; end
```

**Comment by tcort** [comment]
Or even...
```
find . -name \*.md -exec markdown-link-check {} \;
```

**Comment by michaelgwelch** [comment]
Was very excited to find the two work arounds in this issue. But neither appear to work in my environment (a mac).

```
$ find . -name \*.md markdown-link-check {} \;
find: markdown-link-check: unknown primary or operator
```

or 

```
$ find . -iname '*md'| while read file; markdown-link-check $file; end
> 
```

which appears to leave me in a state of waiting for standard input.

It works fine on a single file:

```
$ markdown-link-check README.md 
[✓] releases/alderaan
```

I guess its time to `man find` and figure out what's wrong.

**Comment by tcort** [comment]
> Was very excited to find the two work arounds in this issue. But neither appear to work in my environment (a mac).

In the first one, you're missing `-exec`

**Comment by michaelgwelch** [comment]
Thanks, I just found that by looking at the man pages.
