### ISSUE TITLE
False Positives for Anchor Links to Section Headers Following Fenced Code Blocks

### ISSUE THREAD

**Issue by Kurt-von-Laven** [tcort/markdown-link-check#213]
Section headers that follow an unordered list containing a fenced code block containing a comment are not detected as valid anchor link targets.

**Comment by Kurt-von-Laven** [comment]
markedjs/marked#2483 makes me wonder if this can be fixed simply by updating marked to 4.0.17+.

**Comment by Kurt-von-Laven** [comment]
Now that the upstream issue has been fixed, this issue can be addressed by upgrading marked to 4.0.18+.

**Comment by tcort** [comment]
should be fixed in latest release. if not, please re-open.
