### ISSUE TITLE
Links containing special characters do not work

### ISSUE THREAD

**Issue by kayman-mk** [tcort/markdown-link-check#228]
The following markdown should be valid. But the checker reports a broken link.

```md
# Contributors ✨

[Contributors](#contributors-)
```

Created pull request #227

**Comment by dklimpel** [comment]
This was fixed by #277 ?

**Comment by kayman-mk** [comment]
A really good question. I do not remember the exact problem and my description above could be better ... I will close it.

#227 just adds a test for that. As it is not failing it seems that everything is ok.
