### ISSUE TITLE
404 for valid https-url

### ISSUE THREAD

**Issue by mikelgo** [tcort/markdown-link-check#229]
Hi 👋
first of all: thank you for this awesome tool making my life easier =)

I have an issue that markdown-link-check reports always a  404 for a valid https-url (and i can be pretty sure that they are not down).

I do always get a 404 for any `https://ngrx.io/`-url, eg.
- https://ngrx.io/guide/entity/adapter 
- https://ngrx.io/guide/entity/adapter#adapter-collection-methods 
- and others under this domain

Not pretty sure what to do here. 
I can also provide you a reproduction if you want.

Thanks for your help

Edit: 
I created a reproduction

kindly check out this repository https://github.com/mikelgo/rx-angular/tree/markdown-link-check-repro 
make sure that the branch `markdown-link-check-repro ` is checked out (should be preselected when clicking above linke)

run `yarn nx run docs:check-links`
wait until the command is finished and you should see that there are some broken links detected, all pointing to anything with `https://ngrx-io/**`.

If you click on the links you will notice that they are working correctly

**Comment by nschonni** [comment]
Something is broken on the server with that site, likely because the crawler (and my broweser in the screenshot) have javascript disabled 
![image](https://user-images.githubusercontent.com/1297909/214359043-f5fdd941-6b0f-45a8-b963-75c662f574d6.png)

**Comment by mikelgo** [comment]
Got it. Thank you for pointing this out. 

Means I do not have any chance to fix this I guess 😅

**Comment by nschonni** [comment]
You can use `ignorePatterns` to skip links on those domains, till you can get them to fix their server

**Comment by mikelgo** [comment]
Thanks for that suggestion and your support @nschonni 
I will do this =)

Will also close this issue now.
