### ISSUE TITLE
link-check triggers Error from cloudfront

### ISSUE THREAD

**Issue by dialex** [tcort/markdown-link-check#25]
Both links are working:

- http://amzn.to/2mW1rkx
- http://amzn.to/2mWyt4d

However the 1st one is considered as dead by your tool.

**Comment by tcort** [comment]
http://amzn.to/2mW1rkx leads to a 503 error page with a message containing: `To discuss automated access to Amazon data please contact api-services-support@amazon.com.`

**Comment by dialex** [comment]
Oh again? Then it's kinda related with #23.
Do you make your requests using a "special" method? Because I've tried diff tools and none triggered these DDoS protection systems.

**Comment by NicolasMassart** [comment]
also linked to #109

**Comment by NicolasMassart** [comment]
Will close as duplicate as we have many DDoS prevention tool issues already.
See #23 and #109
