### ISSUE TITLE
Nullpointer without config option

### ISSUE THREAD

**Issue by nhinze23** [tcort/markdown-link-check#254]
`docker run ghcr.io/tcort/markdown-link-check:3.11.1` returns
```                                         
/src/markdown-link-check:99
		input.opts.config = program.opts().config.trim();
		                                         ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at getInputs (/src/markdown-link-check:99:44)
    at main (/src/markdown-link-check:232:20)

Node.js v19.8.1
```

**Comment by voroyam** [comment]
I have the same issue

**Comment by lukasz-madon** [comment]
Happens without docker as well. Workaround:

```js
 markdown-link-check --config config.json ./README.md
```

**Comment by bcdady** [comment]
@tcort I can concur / confirm that I consistently see this error from 3.11.1, but when I run 3.11.0, all seems to function properly. FWIW, I'm testing locally with podman, and have seen these errors in GitLab CI.

**Comment by clagms** [comment]
The main issue with this is that the documentation implies that the config is optional...
