### ISSUE TITLE
Add options for resolving relative paths

### ISSUE THREAD

**Issue by theunrepentantgeek** [tcort/markdown-link-check#256]
Currently, relative paths are resolved relative to the directory containing the markdown file.

If you have the markdown file `/foo/bar/baz.md` and an image `photo.jpg` in the same directory, the image can be referenced simply as `photo.jpg` (or as `./photo.jpg`).

This works perfectly if the markdown file is directly rendered to an HTML file (`baz.md` -> `baz.html`).

However, not all renderers do things that way - both Hugo and Jekyll can render markdown files as directories. One reason for this is that it gives nice URLS where the file type is nicely abstracted away.

In the above example, the file `/foo/bar/baz.md` gets rendered as `/foo/bar/baz/index.html`. 
For the image `/foo/bar/photo.jpg` to be loaded by a browser, it needs to be referenced as `../photo.jpg` because it ends up in the parent directory of the rendered `index.html` file.

When this happens, markdown-link-check reports an error because it thinks that `../photo.jpg` is a broken link. 

Essentially, the directory used by the browser to resolve relative references (`/foo/bar/baz/`) is different to the directory used by the link checker (`/foo/bar/`).

Would you be open to a PR to add an option to make this scenario work?

I'm willing to have a go, but don't want to waste your time (or mine 😁) if this is something you don't want, or if there is already a better solution that I haven't found.

**Comment by nschonni** [comment]
Isn't this already supported with the existing `replacementPatterns` option?

**Comment by theunrepentantgeek** [comment]
I didn't think so - but I may have missed something. I'll go back and have another look, reporting back here afterwards.

**Comment by theunrepentantgeek** [comment]
I've managed to get 95% of the way there using `replacementPatterns`, which is most excellent. 

For the benefit of anyone else wanting to use the checker with Hugo, here's what I've done so far:

``` json
  "replacementPatterns": [
    {
      "pattern": "^\\.\\.\\/",
      "replacement": "./",
      "reason": "Hugo renders files as folders, so strip off leading ../ to become ./"
    },
    {
      "pattern": "^(?<path>(?!http).*\\/)(#.*)?$",
      "replacement": "$<path>_index.md",
      "reason": "Non HTTP/s references to directories should be looking for _index.md files in those folders"
    },
    {
      "pattern": "^(?<path>(?!http).*\\/[\\-_\\w]+)(#.*)?$",
      "replacement": "$<path>.md",
      "reason": "Non HTTP/s references without trailing file types should be .md files"
    }
```

Escaping of regular expressions in JSON makes them very hard to read!

The first rule looks for any URL starting with `../` and changes them to `./`.
E.g. `../related-content` becomes `./related-content`.

The second rule looks for URLs that don't start with `http` (e.g. relative ones), where the path ends in `/` (ignoring any anchor `#` reference), and changes then to end in `_index.md`.
E.g. so `./more-information/` becomes `./more-information/_index.md`

The third rule looks for URLS that don't start with `http` (again, relative ones), where the path ends with a filename, and adds the suffix `.md`.
E.g. so `./more-information` becomes `./more-information.md`

**Comment by theunrepentantgeek** [comment]
I'm wondering about how to handle the last 5%.

When using Hugo, a simple file becomes a folder - so `key-information.md` becomes `key-information/index.html`.

If you want to put related information next to the final file (say, some images), you have to create the directory yourself, and put your content into `_index.md`.
So, we instead have `key-information/_index.md`.

The first of the above `replacementPatterns` does the wrong thing here because the directory already exists, it doesn't get introduced later by Hugo, and we don't want to replace `../` with `./`. 

Do you know of any way for me to suppress a replacement pattern for particular files?
I've read through the source code and haven't found anything, but may have missed it as JS isn't my strong suite.

**Comment by theunrepentantgeek** [comment]
I was unable to configure markdown-link-check to work reliably with Hugo; I have switched to using [htmltest](https://github.com/wjdp/htmltest) to check the generated HTML instead.
