### ISSUE TITLE
Test and failure in CI with active Node.js versions

### ISSUE THREAD

**Issue by MikeMcC399** [tcort/markdown-link-check#291]
The README badge shows permanent failure

 ![Test library workflow status](https://github.com/tcort/markdown-link-check/workflows/Test%20library/badge.svg)

Can this be fixed so the workflow [.github/workflows/ci.yml](https://github.com/tcort/markdown-link-check/blob/master/.github/workflows/ci.yml) runs successfully and tests with currently supported versions of Node.js `18`, `20` and `21`?  (Node.js `14`, `16` and `19` are already end-of-life, see [Node.js release schedule](https://github.com/nodejs/release#release-schedule)).

**Comment by MikeMcC399** [comment]
Judging by the lack of response to this issue, and the fact that there have been no updates / releases since April 2023, it seems like this repo is no longer being maintained.

**Comment by tcort** [comment]
This repository is maintained. Pull requests welcome :)

**Comment by MikeMcC399** [comment]
@tcort 

> This repository is maintained. Pull requests welcome :)

That is good to hear! 👍🏻 

The later versions of Node.js appear to be failing because the server localhost is IPv6 and the code is not handling that format correctly. I will see what I can do about this.

**Comment by MikeMcC399** [comment]
- PR https://github.com/tcort/markdown-link-check/pull/294 is partially addressing this issue.

**Comment by MikeMcC399** [comment]
Thanks to @dklimpel for picking up this issue!

- #296 works around the issue that [test/markdown-link-check.test.js](https://github.com/tcort/markdown-link-check/blob/master/test/markdown-link-check.test.js) is not compatible with the IPv6 loopback address `::1`.

    Starting with Node.js `v17.0.0` the default for Node.js [dns.lookup(hostname[, options], callback)](https://nodejs.org/docs/latest/api/dns.html#dnslookuphostname-options-callback) was changed to `verbatim`, so that depending on the host network configuration the call may return the IPv6 loopback address `::1` instead of the IPv4 address `127.0.0.1`. [test/markdown-link-check.test.js](https://github.com/tcort/markdown-link-check/blob/master/test/markdown-link-check.test.js) doesn't handle the syntax of IPv6 literal addresses correctly. They need to be surrounded by `[]` e.g. `https://[::1]`.

    Adding the NODE_OPTION [`--dns-result-order=ipv4first`](https://nodejs.org/docs/latest/api/cli.html#--dns-result-orderorder) environment variable allows reverting to the `verbatim` `false` setting.

- #295 updates the set of Node.js versions to the currently supported ones.

- Note also the GitHub blog post [GitHub Actions; All Actions will run on Node20 instead of Node16 by default](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) announces that all actions are forced to run under Node.js `20` starting on May 13, 2024. At the moment the workflows produce deprecation warnings. This is a minor issue which can be handled sometime in the next two months.

**Comment by MikeMcC399** [comment]
The deprecation warnings, such as:

> [test (18)](https://github.com/tcort/markdown-link-check/actions/runs/8223841084/job/22486981114)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

would be resolved by merging the dependabot PRs:

- #300 
- #301

**Comment by MikeMcC399** [comment]
This issue is now resolved, see [README](https://github.com/tcort/markdown-link-check/blob/master/README.md):

![Test library workflow status](https://github.com/tcort/markdown-link-check/actions/workflows/ci.yml/badge.svg)

Thanks to @dklimpel for contributions and to @tcort for managing and merging! 👍🏻

The deprecation warnings were not part of the original issue, so they don't prevent closure here.
