### ISSUE TITLE
The linked GitHub action seems to be deprecated by the author

### ISSUE THREAD

**Issue by textPreferred** [tcort/markdown-link-check#341]
Hi, 
It looks as if the GitHub action that your readme [points to](https://github.com/tcort/markdown-link-check#run-in-a-github-action)  has been deprecated by its author (cf. https://github.com/gaurav-nelson/github-action-markdown-link-check/blob/master/README.md) and their new action does no longer make use of `markdown-link-check`.
Maybe you want to remove the link.

Without doing much research, I found that e.g. this action does indeed make of the `markdown-link-check`

**Comment by gaurav-nelson** [comment]
Thank you @textPreferred for creating this issue. Yes, please feel free to remove the link. I'm happy to transfer the project to a maintainer as well.

**Comment by textPreferred** [comment]
PR: https://github.com/tcort/markdown-link-check/pull/345
