### ISSUE TITLE
Dead link error while checking link to a huge markdown file on GitHub

### ISSUE THREAD

**Issue by raipc** [tcort/markdown-link-check#35]
We have some false-positive reports while checking the documentation links from Travis if the target page is huge (e.g. [SQL syntax documentation](https://github.com/axibase/atsd/tree/master/sql) or [Uber](https://uber.com)).
Could you please provide an option to specify timeout after which the link is marked as broken? Also it would be nice to see the reason why the link is considered broken (status code, connection timeout, etc.)

**Comment by NicolasMassart** [comment]
two issues that are now discussed in #72 and fixed by #55 for the verbosity
