### ISSUE TITLE
Version 3.13.5 does not run (docker)

### ISSUE THREAD

**Issue by malcolmdimeglio** [tcort/markdown-link-check#370]
Hi all!

I have been using this repo for some time now and integrated it to my azure pipelines.

I have been running the following command successfully for months: 
`find . -type f -name \*.md -not -path "./build/*" -not -path "./myFolder/*" -not -path "./\.*/*"  -exec docker run --rm -i -v "$(pwd):/tmp:ro" -w /tmp ghcr.io/tcort/markdown-link-check:latest  --alive 203 {} +`

However it appears that today the `stable` version gets me the following:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "markdown-link-check": executable file not found in $PATH: unknown.`

The command I am using hasn't changed since it was working last. Anyone knows what's going on here? Am I missing something?

Thanks for you help!

**Comment by MikeMcC399** [comment]
@malcolmdimeglio 

In an effort to work around another issue, `markdown-link-check` was moved to a sub-directory `bin`.

The issue with the Docker image is also reproducible using the exact instructions from https://github.com/tcort/markdown-link-check/blob/master/README.md#run-using-docker

```shell
git clone https://github.com/tcort/markdown-link-check
cd markdown-link-check
docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
```

```text
$ docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "markdown-link-check": executable file not found in $PATH: unknown.
```

## Workarounds

1. Pin to previous working version, for example

    ```shell
    docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:3.12.2 /tmp/README.md
    ```

2. Run `markdown-link-check` from moved location

    ```shell
    docker run -v ${PWD}:/tmp:ro --rm -i --entrypoint bin/markdown-link-check ghcr.io/tcort/markdown-link-check:3.13.5 /tmp/README.md
    ```

**Comment by malcolmdimeglio** [comment]
I ended up pinning it to the version 3.12.2 and that solved my issue.

Is the new entry point the new expected behavior or will it eventually change/revert back to what it was before? Just asking to know if I should just start pinning my versions or if I can just change the `--entrypoint` and keep the `stable` tag

Thanks for the explanation though!

**Comment by MikeMcC399** [comment]
@malcolmdimeglio 

> I ended up pinning it to the version 3.12.2 and that solved my issue.

Good!

> Is the new entry point the new expected behavior or will it eventually change/revert back to what it was before? Just asking to know if I should just start pinning my versions or if I can just change the --entrypoint and keep the stable tag

- There were multiple attempts yesterday to fix https://github.com/tcort/markdown-link-check/issues/368. The last entry was https://github.com/tcort/markdown-link-check/issues/368#issuecomment-2457594027 and the question about what happens next would need to be answered by @tcort I guess.

**Comment by tcort** [comment]
I'll move the script back to its original entry point.
