### ISSUE TITLE
return exit code zero on success

### ISSUE THREAD

**Issue by codefromthecrypt** [tcort/markdown-link-check#377]
I have found markdown-link-check returning exit code 1 on files that pass link checks. I noticed in[ another project](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/75ceb5598807a8bb5c45d4d4f734ce2f6c88d25c/Makefile.Common#L207), people doing `markdown-link-check ... || true` to avoid this.

However, I would like to have exit code 1 when there is a real failure. Is this a bug?

```bash
$ markdown-link-check -V
3.13.6

$ markdown-link-check -v -c ./build-bin/mlc_config.json ./zipkin-junit5/README.md

FILE: ./zipkin-junit5/README.md

$ echo $?
1
```

**Comment by isuftin** [comment]
@codefromthecrypt  - I think your issue is due to md link check 3.13.x is broken when using a config file - See https://github.com/tcort/markdown-link-check/issues/369

**Comment by codefromthecrypt** [comment]
@isuftin indeed thanks!
