### ISSUE TITLE
Image size instructions not working

### ISSUE THREAD

**Issue by timmkrause** [tcort/markdown-link-check#42]
I am currently not sure if this is a standard, haven't done any research on that yet but our VSTS Wiki supports the following image resizing instruction:

    ![name](files/some-file.png =20%x)

This causes some "malicious" error during the check.
These instructions should be removed and then passed to the check I think.

**Comment by timmkrause** [comment]
Thanks for pointing this out. As I'd like to start with the glob feature, would you mind taking care of this? Or don't you have the capacity to do so?

**Comment by timmkrause** [comment]
Because of weird debugging experiences (working here, not working there, WTF moments...) I found out that these kinds of image links were extracted by `markdown-link-extractor` until `marked` version 0.3.19.
So the hook in `markdown-link-extractor` to remove the instruction does not work anymore since version 0.4.0.
Because their goal is to align with the GFM/CommonMark standards I think they removed it intentionally.

https://github.com/markedjs/marked/issues/1279

**Comment by tcort** [comment]
I've published v3.5.4 which depends on the improved markdown-link-extractor. If this isn't solved, please re-open the issue.
