### ISSUE TITLE
E-mail address validation fails with query string

### ISSUE THREAD

**Issue by nschonni** [tcort/markdown-link-check#47]
Don't have a live failure example at the moment, but I grabbed this one from https://en.wikipedia.org/wiki/Mailto
```
someone@example.com?subject=This%20is%20the%20subject&cc=someone_else@example.com&body=This%20is%20the%20body
```
Maybe just split on the `?` since the `ismail` library only seems to care about the address format part.

**Comment by tcort** [comment]
Fix published in `v3.5.5`
