### ISSUE TITLE
Query strings after `.md` links get marked as failed

### ISSUE THREAD

**Issue by nschonni** [tcort/markdown-link-check#49]
Not sure if the behaviour is correct, but if you have query string after a link to another markdown file, it will always fail.
EX: 
```markdown
[Markdown with query](myfile.md?foo=bar)
```
I think this is used so that the final generated link also includes the query string, but I'm not sure if it actually valid markdown

**Comment by tcort** [comment]
I think this is also going to be an issue with fragments `[section 1](book.md#section-1)`. It seems valid to me. Someone could have a webserver configured to process `.md` files (kind of like how `.php` files are processed with `php` via the webserver) and I suppose you could want to check those links offline.

This is best solved in the `file://` protocol handler in [link-check](https://github.com/tcort/link-check). It should be straightforward to parse the file link with the `url` module and then stringify/format it without the fragment nor search parts. Ideally, I'd use [url.format(URL, { fragment: false, search: false })](https://nodejs.org/docs/latest/api/url.html#url_url_format_url_options), but I think I'll stick to the legacy API for now as node 6 (LTS until April 2019) doesn't support the new API. I hope to get to this tonight.

**Comment by tcort** [comment]
The fix was simpler than I thought. `link-check` was using `.path` (includes query string) rather than `.pathname` (omits query string). See https://nodejs.org/docs/latest/api/url.html#url_url_strings_and_url_objects

Published in v3.6.1
