### ISSUE TITLE
bash: markdown-link-check: command not found

### ISSUE THREAD

**Issue by hugovk** [tcort/markdown-link-check#5]
Following the README:

```bash
$ npm install --save markdown-link-check
botwiki@1.0.0 /Users/hugo/github/botwiki.org
└── markdown-link-check@1.2.0 

npm WARN botwiki@1.0.0 No repository field.

$ markdown-link-check ./README.md
-bash: markdown-link-check: command not found

$ git diff package.json
diff --git a/package.json b/package.json
index 2abbf91..e536ece 100644
--- a/package.json
+++ b/package.json
@@ -3,7 +3,9 @@
   "version": "1.0.0",
   "description": "Bots! Bots everywhere!",
   "main": "index.php",
-  "dependencies": {},
+  "dependencies": {
+    "markdown-link-check": "^1.2.0"
+  },
   "devDependencies": {
     "browser-sync": "^2.7.13",
     "connect-livereload": "^0.4.0",
```

Am I missing something?

**Comment by hugovk** [comment]
It works after `npm install -g markdown-link-check`. 

Should it work after `npm install --save markdown-link-check`?

**Comment by tcort** [comment]
> Should it work after `npm install --save markdown-link-check`?

This is the command for adding the module to your project. This allows for several interesting scenarios:
* have a script in your project's `package.json` to automatically check the links in the `README.md` file.
* add link checking capabilities to your project (e.g. maybe your project is a markdown editor).

For installing the command line tool into your `PATH`, yes `npm install -g markdown-link-check` is the command you want.

I listed both commands in the [installation section of the README.md](https://github.com/tcort/markdown-link-check#installation). If it isn't clear enough, please let me know.
