### ISSUE TITLE
Exit 1 if errors are found

### ISSUE THREAD

**Issue by iamdanfox** [tcort/markdown-link-check#57]
## Current behaviour

I'm using `markdown-link-check` on CI but the build is always green, even if the script finds broken links.

```
find . -name \*.md -exec markdown-link-check {} \;
```

## Desired behaviour

`markdown-link-check` should exit 1 if a broken link is found, ensuring that CI builds will go red.

_EDIT - it seems `markdown-link-check` already exits 1 if an error is found, it's just the usage within `find -exec` that suppresses errors._

**Comment by iamdanfox** [comment]
Short-term workaround:

```
find . -name \*.md | xargs -n 1 markdown-link-check -c .circleci/markdown-link-check-config.json
```

**Comment by allencloud** [comment]
+1
I have met the same issue. If we need to integrate this in CI system, I think it is better to exit non-zero if invalid link exists. Otherwise user needs to construct a manual command to return non-zero exit code, which is somewhat inconvenient.

**Comment by philsturgeon** [comment]
Got it working with: 

```
OUTPUT=$(yarn run link-check); [[ $OUTPUT != *ERROR* ]] && echo \"$OUTPUT\" && exit 1` 
```

Dumb or genius I dunno, it works.
