### ISSUE TITLE
Support Non-relative Paths in Github Markdown

### ISSUE THREAD

**Issue by ericKlawitter** [tcort/markdown-link-check#68]
Hello,

Use cases where READMEs have a link in the format /foo/bar/README.md fail markdown-link-check, with the error, "dead links found!". Github et al understands this type of link as being in the foo/bar location from the top of the repo. This is a pain point for repos who have deep paths (e.g., writing a ../../../foo/bar relative path) or are introducing this tool to an existing repo utilizing this format. Is it possible for markdown-link-check to support this type of link?

Thanks.

**Comment by ericKlawitter** [comment]
Ah, I see this as an optional parameter for the API -- is `baseUrl` usable through the CLI? I don't see that under `options` in the CLI section of the documentation. 

Thanks.

**Comment by nschonni** [comment]
Yeah, think you'd need to set in in a config file, and pass that through the CLI

**Comment by ericKlawitter** [comment]
Thanks for the quick response.

**Comment by banzo** [comment]
Wouldn't this only work for one branch?
i.e. baseUrl can be `https://github.com/banzo/<repo_name>/blob/<branch_name>/ `

If this option was available in the Github Actions workflow yaml, maybe it would be possible to inject the branch the workflow is running: `https://github.com/banzo/<repo_name>/blob/${GITHUB_REF##*/}/`
