### ISSUE TITLE
Feature request: Command line argument to check external or internal links only

### ISSUE THREAD

**Issue by gaurav-nelson** [tcort/markdown-link-check#73]
By default markdown link check, checks all links internal and external. It will be helpful if we add a switch that allow check only external links, only internal links.

```bash
$ markdown-link-check README.md --internal-only

$ markdown-link-check README.md --external-only
```

PS: 😃 
We do have room for it:
```
Usage: markdown-link-check [options] [filenameOrUrl]

  Options:
    -p, --progress               show progress bar
    -c, --config [config]        apply a configuration file (JSON)
    -q, --quiet                  display errors only
    -v, --verbose                displays detailed error information 
    -h, --help                   output usage information
    -i, --internal-only          check internal links only
    -e, --external-only          check external links only
```

**Comment by guivinson** [comment]
Got the same need but you can already do it with two different dedicated config files: for example for internal check only:

`markdown-link-check --config=internal-only.json`

where internal-only.json could be the following:
`{
    "ignorePatterns": [
        {
            "pattern": "^https?:\/\/.*"
        }
    ]
}`

**Comment by NicolasMassart** [comment]
Internal links could also be excluded using the same pattern strategy but by excluding all link without http/https.
You can use the following pattern:
```
^(?!http)
```
