### ISSUE TITLE
vulnerability advisory for package due to markdown-link-extractor dependency

### ISSUE THREAD

**Issue by rajsite** [tcort/markdown-link-check#74]
markdown-link-check reports a vulnerability in the `npm audit` tool due to the markdown-link-extractor dependency and it's transitive dependency on marked@0.4.0.

I reported the issue in the markdown-link-extractor repo here: https://github.com/tcort/markdown-link-extractor/issues/5

And hopefully if that issue is resolved this one could be too :)

**Comment by tcort** [comment]
Updated and released v3.7.3
