### ISSUE TITLE
Feature Request: check whether internal links correspond to a name/id

### ISSUE THREAD

**Issue by mikesamuel** [tcort/markdown-link-check#75]
Some markdown documents have far more internal fragment links than external.  It'd be nice if those could be sanity checked.

```js
// Ideally would error since there is no #foo
markdownLinkCheck(
    `[example](#foo)`,
    (err, results) => { ... })

// No error since there is an explicit name created
markdownLinkCheck(
    `
<a name="foo"> foo </a>

[example](#foo)`,
    (err, results) => { ... })

// No error since there is a link target based on header auto-linking
markdownLinkCheck(
    `
# foo

[example](#foo)`,
    (err, results) => { ... })
```

**Comment by NicolasMassart** [comment]
@mikesamuel Could this issue be merged with #91 in your opinion?

**Comment by mikesamuel** [comment]
@NicolasMassart Yes.  It looks like Joel's output catches same-document anchors:

    [✖] #user-content-query---v3-search-endpoint

**Comment by NicolasMassart** [comment]
Thanks. Let's say it's a duplicate then (no offense!)

**Comment by mikesamuel** [comment]
@NicolasMassart No offense taken.  Thanks for markdown-link-check.
