### ISSUE TITLE
Doesn’t work with new Twitter

### ISSUE THREAD

**Issue by ai** [tcort/markdown-link-check#79]
Thanks for your amazing tool. But I recently found that the tool has some conflict with new Twitter.

```sh
echo "[@twitter](https://twitter.com/logux_io)" > test.md
npx markdown-link-check test.md                            

FILE: test.md
[✖] https://twitter.com/logux_io

ERROR: dead links found!
```

**Comment by NicolasMassart** [comment]
Could you try with a more verbose mode to display the error code returned by twitter please?

**Comment by NicolasMassart** [comment]
What I have is :
```bash
nicolas@ethy markdown-link-check % echo "[@twitter](https://twitter.com/logux_io)" > test.md
npx markdown-link-check test.md
npx: installed 66 in 2.768s

FILE: test.md
[✓] https://twitter.com/logux_io

1 links checked.
```
So unless someone can reproduce, I will mark this one as invalid. Thanks for your understanding.

**Comment by nschonni** [comment]
I've been seeing errors in general connecting to Twitter lately, but maybe they are rolling out something that isn't affecting all requests yet
![image](https://user-images.githubusercontent.com/1297909/94954971-d8eeff80-04b7-11eb-910b-efaaa4f8999c.png)

```
Failed to load ‘https://twitter.com/logux_io’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
```

This is in Firefox in the browser, but may indicate an upcoming issue to requests in general.

**Comment by NicolasMassart** [comment]
It's probably something outside of our scope here.
