### ISSUE TITLE
An option to insert a delay between requests

### ISSUE THREAD

**Issue by CreepySkeleton** [tcort/markdown-link-check#85]
[`crates.io` has request rate limitations](https://crates.io/policies#crawlers). When markdown-link-check tries to check those links many of them fail (404).

I propose to introduce a new config option: 
```json
{
    "rate_limit": [
        {
            "urls": [
                "https://example.com"
            ],
            "timeout": "1000 (milliseconds)"
        }
    ]
}
```

**Comment by NicolasMassart** [comment]
Is crates.io returning a retry later 429 code in you case?

**Comment by CreepySkeleton** [comment]
I don't remember. I do remember that we solved it by adding the `Accept: text/html` header, so it was probably 404.

**Comment by NicolasMassart** [comment]
Is this enhancement still useful? To me if your iste has a rate limit, it should be handled by the "retry on 429" feature (not released but un master, see 9f50271

**Comment by CreepySkeleton** [comment]
Well, not to me, not anymore, but I can see how it can be useful, potentially. Thank you @tcort for your work!

**Comment by NicolasMassart** [comment]
please reopen if needed
