### ISSUE TITLE
fails on validating emails when in <>

### ISSUE THREAD

**Issue by NicolasMassart** [tcort/markdown-link-check#86]
Hi,
I tried to validate a file with an email address link of the form `<test@test.com>` which renders well (in html it give `<a href="mailto:test@test.com">test@test.com</a>` and is markdown compliant, but link checker sees it as `mailto:&#116;&#x65;&#x73;&#116;&#64;&#116;&#101;&#x73;&#116;&#x2e;&#99;&#x6f;&#x6d;` and fails validating it.
Can you help me?

**Comment by waylan** [comment]
Same problem here for me.

**Comment by tcort** [comment]
Fixed in v3.8.3
