### ISSUE TITLE
Output more error details to stderr

### ISSUE THREAD

**Issue by koppor** [tcort/markdown-link-check#87]
When redirecting the output to a file, the console sill prints out following messages:

```bash
$ find . -name \*.md -exec markdown-link-check -qq {} \; > bad-links.txt

ERROR: 1 dead links found!

ERROR: 1 dead links found!

ERROR: 1 dead links found!

ERROR: 2 dead links found!

ERROR: 4 dead links found!
```

Maybe, the filename and the concrete errors could also be put out to the console. This would be a step towards #77.

**Comment by NicolasMassart** [comment]
Did you try the [tee shell command](https://man7.org/linux/man-pages/man1/tee.1.html) to split your output and send in a file and on a terminal at the same time?

I use something like:
`find . -name \*.md ! -path "./node_modules/*" -exec ./node_modules/markdown-link-check/markdown-link-check -qq -c link_check_conf.json {} \; 2>&1 | tee linkchecker.log`
