### ISSUE TITLE
problem with relative links when markdown-link-check is used in Github Actions

### ISSUE THREAD

**Issue by bedroesb** [tcort/markdown-link-check#96]
Hello everyone,

I am a happy user of the markdown link checker on my  Jekyll project using GitHub Actions. 
Now is github link checker complaining about relative links in the markdown file like this:

```
[README file](documentation_for_metadata.html)
```
gives this error:
```
[✖] documentation_for_metadata.html → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/pages/documentation_for_metadata.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/pages/documentation_for_metadata.html'
}
```
Although the page exists: https://elixir-belgium.github.io/data_management_hub/documentation_for_metadata.html

The API supports the property `baseUrl` but this seems not to be parsed out of the config.json file.

Am I doing something wrong or is this feature to be implemented ?

Project with the problem: https://github.com/ELIXIR-Belgium/data_management_hub

**Comment by gaurav-nelson** [comment]
@bedroesb For checking internal links `markdown-link-check` checks if the file exist. In your case, it is checking for the file `documentation_for_metadata.html` and failing because there is no file with `.html` extension. 

You can try fixing the link to `[README file](documentation_for_metadata.md)`.

**Comment by zivl** [comment]
@gaurav-nelson is this checking only `*.md` files?
I have something similar with relative `*.js` files (it doesn't work also locally, not on Github Action)

**Comment by gaurav-nelson** [comment]
@zivl Yes its for checking markdown files only. 
- Do you mean you have a link to `somefile.js` in a markdown files and you get errors related to that?

**Comment by bedroesb** [comment]
@gaurav-nelson In the case of a jekyll website, referring to the markdownfiles is also not really an option, since I want to refer to the html files that are build out of the markdowns. I would like to set the base URL for internal links myself, instead of the default chosen one being `/github/workspace/pages/`

**Comment by gaurav-nelson** [comment]
@bedroesb Maybe you can get away with [replacementPatterns](https://github.com/tcort/markdown-link-check#config-file-format)

```json
{
"replacementPatterns": [
		{
			"pattern": "data_documentation",
			"replacement": "data_documentation.md"
		}
	]
}
```

Can you share your configuration file? and also links to sample files with failing links?

**Comment by NicolasMassart** [comment]
Hi @bedroesb any news on this one?

**Comment by cadeef** [comment]
I do something like this in my config for relative links on my Hugo-built site:

``` json
{
	"replacementPatterns": [
		{
			"pattern": "^/",
			"replacement": "https://example.com/"
		}
	]
}
```
It works well. There's surely edge cases where it might cause a problem, but it hasn't *yet*.

**Comment by NicolasMassart** [comment]
I vote that we consider replacement patterns the way to deal with that issue

**Comment by NicolasMassart** [comment]
@bedroesb please re-open if needed
